# fly.toml app configuration file generated for potato-test on 2023-05-17T10:38:54-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "potato-test"
primary_region = "sea"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
